// make sure to leave the o master node!!
export const data_pop = [
  {
    ColA: "0",
    ColB: "0",
    ColC: "0",
    ColD: "0",
    ColE: "0",
    ColF: "0",
    Title: "MasterNode",
    Link: "https://google.com",
    LongDescription: "MasterNode",
    SummaryDescription: "MasterNode",
    ParentNodeString: "0",
    OriginalNumber: "0",
  },
  {
    ColA: "1",
    ColB: "",
    ColC: "",
    ColD: "",
    ColE: "",
    ColF: "",
    Title: "Assessments and reports ",
    Link: " https://ehgdev.atlassian.net/wiki/spaces/SYNMAIN/pages/2294710291/Assessments+and+reports ",
    LongDescription: "long desc",
    SummaryDescription: "summary",
    ParentNodeString: "0",
    OriginalNumber: "1",
    GroupingID: "1729",
  },
  {
    ColA: "",
    ColB: "1.1",
    ColC: "",
    ColD: "",
    ColE: "",
    ColF: "",
    Title: "Assessments and reports Overview ",
    Link: " https://ehgdev.atlassian.net/wiki/spaces/SYNMAIN/pages/2294711167/Assessments+and+reports+Overview",
    LongDescription: "",
    SummaryDescription: "summary",
    ParentNodeString: "1",
    OriginalNumber: "1.1",
    GroupingID: "1729",
  },
  {
    ColA: "",
    ColB: "1.2",
    ColC: "",
    ColD: "",
    ColE: "",
    ColF: "",
    Title: "What's new to Assessments and reports ",
    Link: " https://ehgdev.atlassian.net/wiki/spaces/SYNMAIN/pages/2294738607/What%27s+new+to+Assessments+and+reports",
    LongDescription: "",
    SummaryDescription: "summary",
    ParentNodeString: "1",
    OriginalNumber: "1.2",
    GroupingID: "1729",
  },
  {
    ColA: "",
    ColB: "1.3",
    ColC: "",
    ColD: "",
    ColE: "",
    ColF: "",
    Title: "Concepts used in student assessments ",
    Link: " https://ehgdev.atlassian.net/wiki/spaces/SYNMAIN/pages/2294711168/Concepts+used+in+student+assessments",
    LongDescription: "",
    SummaryDescription: "summary",
    ParentNodeString: "1",
    OriginalNumber: "1.3",
    GroupingID: "1729",
  },
  {
    ColA: "",
    ColB: "1.4",
    ColC: "",
    ColD: "",
    ColE: "",
    ColF: "",
    Title: "Victorian Curriculum F-10 ",
    Link: " https://ehgdev.atlassian.net/wiki/spaces/SYNMAIN/pages/2294736348/Victorian+Curriculum+F-10",
    LongDescription: "",
    SummaryDescription: "summary",
    ParentNodeString: "1",
    OriginalNumber: "1.4",
    GroupingID: "1729",
  },
  {
    ColA: "",
    ColB: "",
    ColC: "1.4.1",
    ColD: "",
    ColE: "",
    ColF: "",
    Title: "Victorian Curriculum frameworks ",
    Link: " https://ehgdev.atlassian.net/wiki/spaces/SYNMAIN/pages/2294736370/Victorian+Curriculum+frameworks",
    LongDescription: "",
    SummaryDescription: "summary",
    ParentNodeString: "1.4",
    OriginalNumber: "1.4.1",
    GroupingID: "1729",
  },
  {
    ColA: "",
    ColB: "",
    ColC: "",
    ColD: "1.4.1.1",
    ColE: "",
    ColF: "",
    Title: "Maintaining Victorian Curriculum frameworks ",
    Link: " https://ehgdev.atlassian.net/wiki/spaces/SYNMAIN/pages/2294736369/Maintaining+Victorian+Curriculum+frameworks",
    LongDescription: "",
    SummaryDescription: "summary",
    ParentNodeString: "1.4.1",
    OriginalNumber: "1.4.1.1",
    GroupingID: "1729",
  },
  {
    ColA: "",
    ColB: "",
    ColC: "1.4.2",
    ColD: "",
    ColE: "",
    ColF: "",
    Title: "Victorian Curriculum reporting requirements ",
    Link: " https://ehgdev.atlassian.net/wiki/spaces/SYNMAIN/pages/2294741917/Victorian+Curriculum+reporting+requirements",
    LongDescription: "",
    SummaryDescription: "summary",
    ParentNodeString: "1.4",
    OriginalNumber: "1.4.2",
    GroupingID: "1729",
  },
  {
    ColA: "",
    ColB: "",
    ColC: "1.4.3",
    ColD: "",
    ColE: "",
    ColF: "",
    Title: "Configuring the Victorian Curriculum ",
    Link: " https://ehgdev.atlassian.net/wiki/spaces/SYNMAIN/pages/2294741920/Configuring+the+Victorian+Curriculum",
    LongDescription: "",
    SummaryDescription: "summary",
    ParentNodeString: "1.4",
    OriginalNumber: "1.4.3",
    GroupingID: "1729",
  },
  {
    ColA: "",
    ColB: "",
    ColC: "1.4.4",
    ColD: "",
    ColE: "",
    ColF: "",
    Title: "Entering Victorian Curriculum results ",
    Link: " https://ehgdev.atlassian.net/wiki/spaces/SYNMAIN/pages/2294736398/Entering+Victorian+Curriculum+results",
    LongDescription: "",
    SummaryDescription: "summary",
    ParentNodeString: "1.4",
    OriginalNumber: "1.4.4",
    GroupingID: "1729",
  },
  {
    ColA: "",
    ColB: "",
    ColC: "",
    ColD: "1.4.4.1",
    ColE: "",
    ColF: "",
    Title: "Adding the DNP result to the luReportResultType lookup table ",
    Link: " https://ehgdev.atlassian.net/wiki/spaces/SYNMAIN/pages/2294736397/Adding+the+DNP+result+to+the+luReportResultType+lookup+table",
    LongDescription: "",
    SummaryDescription: "summary",
    ParentNodeString: "1.4.4",
    OriginalNumber: "1.4.4.1",
    GroupingID: "1729",
  },
  {
    ColA: "",
    ColB: "",
    ColC: "1.4.5",
    ColD: "",
    ColE: "",
    ColF: "",
    Title: "Related information for Victorian Curriculum ",
    Link: " https://ehgdev.atlassian.net/wiki/spaces/SYNMAIN/pages/2294741929/Related+information+for+Victorian+Curriculum",
    LongDescription: "",
    SummaryDescription: "summary",
    ParentNodeString: "1.4",
    OriginalNumber: "1.4.5",
    GroupingID: "1729",
  },
  {
    ColA: "",
    ColB: "1.5",
    ColC: "",
    ColD: "",
    ColE: "",
    ColF: "",
    Title: "Maintaining curriculum frameworks ",
    Link: " https://ehgdev.atlassian.net/wiki/spaces/SYNMAIN/pages/2294736408/Maintaining+curriculum+frameworks",
    LongDescription: "curriculum framework",
    SummaryDescription: "summary",
    ParentNodeString: "1",
    OriginalNumber: "1.5",
    GroupingID: "365",
  },
  {
    ColA: "",
    ColB: "",
    ColC: "1.5.1",
    ColD: "",
    ColE: "",
    ColF: "",
    Title: "Using the Subject Assessment Other Definition Maintenance window ",
    Link: " https://ehgdev.atlassian.net/wiki/spaces/SYNMAIN/pages/2294736410/Using+the+Subject+Assessment+Other+Definition+Maintenance+window",
    LongDescription: "",
    SummaryDescription: "summary",
    ParentNodeString: "1.5",
    OriginalNumber: "1.5.1",
    GroupingID: "365",
  },
  {
    ColA: "",
    ColB: "",
    ColC: "",
    ColD: "1.5.1.1",
    ColE: "",
    ColF: "",
    Title: "Loading pre-defined curriculum frameworks ",
    Link: " https://ehgdev.atlassian.net/wiki/spaces/SYNMAIN/pages/2294736424/Loading+pre-defined+curriculum+frameworks",
    LongDescription: "",
    SummaryDescription: "summary",
    ParentNodeString: "1.5.1",
    OriginalNumber: "1.5.1.1",
    GroupingID: "365",
  },
  {
    ColA: "",
    ColB: "",
    ColC: "",
    ColD: "1.5.1.2",
    ColE: "",
    ColF: "",
    Title: "Copying existing curriculum frameworks to new years ",
    Link: " https://ehgdev.atlassian.net/wiki/spaces/SYNMAIN/pages/2294736436/Copying+existing+curriculum+frameworks+to+new+years",
    LongDescription: "",
    SummaryDescription: "summary",
    ParentNodeString: "1.5.1",
    OriginalNumber: "1.5.1.2",
    GroupingID: "365",
  },
  {
    ColA: "",
    ColB: "",
    ColC: "",
    ColD: "1.5.1.3",
    ColE: "",
    ColF: "",
    Title: "Manually adding custom levels to curriculum frameworks ",
    Link: " https://ehgdev.atlassian.net/wiki/spaces/SYNMAIN/pages/2294736445/Manually+adding+custom+levels+to+curriculum+frameworks",
    LongDescription: "",
    SummaryDescription: "summary",
    ParentNodeString: "1.5.1",
    OriginalNumber: "1.5.1.3",
    GroupingID: "365",
  },
  {
    ColA: "",
    ColB: "1.6",
    ColC: "",
    ColD: "",
    ColE: "",
    ColF: "",
    Title: "Maintaining subject assessments ",
    Link: " https://ehgdev.atlassian.net/wiki/spaces/SYNMAIN/pages/2294711169/Maintaining+subject+assessments",
    LongDescription: "learning area",
    SummaryDescription: "summary",
    ParentNodeString: "1",
    OriginalNumber: "1.6",
    GroupingID: "1065",
  },
  {
    ColA: "",
    ColB: "",
    ColC: "1.6.1",
    ColD: "",
    ColE: "",
    ColF: "",
    Title: "Searching for subjects and assessment areas ",
    Link: " https://ehgdev.atlassian.net/wiki/spaces/SYNMAIN/pages/2294711171/Searching+for+subjects+and+assessment+areas",
    LongDescription: "",
    SummaryDescription: "summary",
    ParentNodeString: "1.6",
    OriginalNumber: "1.6.1",
    GroupingID: "1065",
  },
  {
    ColA: "",
    ColB: "",
    ColC: "1.6.2",
    ColD: "",
    ColE: "",
    ColF: "",
    Title: "Creating new subject assessments ",
    Link: " https://ehgdev.atlassian.net/wiki/spaces/SYNMAIN/pages/2294711170/Creating+new+subject+assessments",
    LongDescription: "",
    SummaryDescription: "summary",
    ParentNodeString: "1.6",
    OriginalNumber: "1.6.2",
    GroupingID: "1065",
  },
  {
    ColA: "",
    ColB: "",
    ColC: "1.6.3",
    ColD: "",
    ColE: "",
    ColF: "",
    Title: "Subject Assessment Maintenance - Summary tab - Summary sub-tab ",
    Link: " https://ehgdev.atlassian.net/wiki/spaces/SYNMAIN/pages/2294711172/Subject+Assessment+Maintenance+-+Summary+tab+-+Summary+sub-tab",
    LongDescription: "",
    SummaryDescription: "summary",
    ParentNodeString: "1.6",
    OriginalNumber: "1.6.3",
    GroupingID: "1065",
  },
  {
    ColA: "",
    ColB: "",
    ColC: "1.6.4",
    ColD: "",
    ColE: "",
    ColF: "",
    Title: "Subject Assessment Maintenance - Summary tab - Comments sub-tab ",
    Link: " https://ehgdev.atlassian.net/wiki/spaces/SYNMAIN/pages/2294711174/Subject+Assessment+Maintenance+-+Summary+tab+-+Comments+sub-tab",
    LongDescription: "",
    SummaryDescription: "summary",
    ParentNodeString: "1.6",
    OriginalNumber: "1.6.4",
    GroupingID: "1065",
  },
  {
    ColA: "",
    ColB: "",
    ColC: "",
    ColD: "1.6.4.1",
    ColE: "",
    ColF: "",
    Title: "Comment bank ",
    Link: " https://ehgdev.atlassian.net/wiki/spaces/SYNMAIN/pages/2294711173/Comment+bank",
    LongDescription: "",
    SummaryDescription: "summary",
    ParentNodeString: "1.6.4",
    OriginalNumber: "1.6.4.1",
    GroupingID: "1065",
  },
  {
    ColA: "",
    ColB: "",
    ColC: "",
    ColD: "1.6.4.2",
    ColE: "",
    ColF: "",
    Title: "Loading and copying existing comments ",
    Link: " https://ehgdev.atlassian.net/wiki/spaces/SYNMAIN/pages/2294711176/Loading+and+copying+existing+comments",
    LongDescription: "",
    SummaryDescription: "summary",
    ParentNodeString: "1.6.4",
    OriginalNumber: "1.6.4.2",
    GroupingID: "1065",
  },
  {
    ColA: "",
    ColB: "",
    ColC: "1.6.5",
    ColD: "",
    ColE: "",
    ColF: "",
    Title: "Subject Assessment Maintenance - Summary tab - Mark Book sub-tab ",
    Link: " https://ehgdev.atlassian.net/wiki/spaces/SYNMAIN/pages/2294711175/Subject+Assessment+Maintenance+-+Summary+tab+-+Mark+Book+sub-tab",
    LongDescription: "",
    SummaryDescription: "summary",
    ParentNodeString: "1.6",
    OriginalNumber: "1.6.5",
    GroupingID: "1065",
  },
  {
    ColA: "",
    ColB: "",
    ColC: "",
    ColD: "1.6.5.1",
    ColE: "",
    ColF: "",
    Title:
      "Importing mark book assessments from Subject Assessment Maintenance ",
    Link: " https://ehgdev.atlassian.net/wiki/spaces/SYNMAIN/pages/2294711179/Importing+mark+book+assessments+from+Subject+Assessment+Maintenance",
    LongDescription: "",
    SummaryDescription: "summary",
    ParentNodeString: "1.6.5",
    OriginalNumber: "1.6.5.1",
    GroupingID: "1065",
  },
  {
    ColA: "",
    ColB: "",
    ColC: "1.6.6",
    ColD: "",
    ColE: "",
    ColF: "",
    Title: "Subject Assessment Maintenance - Summary tab - Classes sub-tab ",
    Link: " https://ehgdev.atlassian.net/wiki/spaces/SYNMAIN/pages/2294711178/Subject+Assessment+Maintenance+-+Summary+tab+-+Classes+sub-tab",
    LongDescription: "",
    SummaryDescription: "summary",
    ParentNodeString: "1.6",
    OriginalNumber: "1.6.6",
    GroupingID: "1065",
  },
  {
    ColA: "",
    ColB: "",
    ColC: "1.6.7",
    ColD: "",
    ColE: "",
    ColF: "",
    Title: "Subject Assessment Maintenance - Summary tab - Targets sub-tab ",
    Link: " https://ehgdev.atlassian.net/wiki/spaces/SYNMAIN/pages/2294711177/Subject+Assessment+Maintenance+-+Summary+tab+-+Targets+sub-tab",
    LongDescription: "",
    SummaryDescription: "summary",
    ParentNodeString: "1.6",
    OriginalNumber: "1.6.7",
    GroupingID: "1065",
  },
  {
    ColA: "",
    ColB: "",
    ColC: "1.6.8",
    ColD: "",
    ColE: "",
    ColF: "",
    Title: "Subject Assessment Maintenance - Summary tab - Security sub-tab ",
    Link: " https://ehgdev.atlassian.net/wiki/spaces/SYNMAIN/pages/2294711182/Subject+Assessment+Maintenance+-+Summary+tab+-+Security+sub-tab",
    LongDescription: "",
    SummaryDescription: "summary",
    ParentNodeString: "1.6",
    OriginalNumber: "1.6.8",
    GroupingID: "1065",
  },
  {
    ColA: "",
    ColB: "",
    ColC: "1.6.9",
    ColD: "",
    ColE: "",
    ColF: "",
    Title: "Renaming subject assessments ",
    Link: " https://ehgdev.atlassian.net/wiki/spaces/SYNMAIN/pages/2294711181/Renaming+subject+assessments",
    LongDescription: "",
    SummaryDescription: "summary",
    ParentNodeString: "1.6",
    OriginalNumber: "1.6.9",
    GroupingID: "1065",
  },
  {
    ColA: "",
    ColB: "",
    ColC: "1.6.10",
    ColD: "",
    ColE: "",
    ColF: "",
    Title: "Copying subject assessments ",
    Link: " https://ehgdev.atlassian.net/wiki/spaces/SYNMAIN/pages/2294711180/Copying+subject+assessments",
    LongDescription: "",
    SummaryDescription: "summary",
    ParentNodeString: "1.6",
    OriginalNumber: "1.6.10",
    GroupingID: "1065",
  },
  {
    ColA: "",
    ColB: "",
    ColC: "1.6.11",
    ColD: "",
    ColE: "",
    ColF: "",
    Title: "Moving subject assessments ",
    Link: " https://ehgdev.atlassian.net/wiki/spaces/SYNMAIN/pages/2294711185/Moving+subject+assessments",
    LongDescription: "",
    SummaryDescription: "summary",
    ParentNodeString: "1.6",
    OriginalNumber: "1.6.11",
    GroupingID: "1065",
  },
  {
    ColA: "",
    ColB: "",
    ColC: "1.6.12",
    ColD: "",
    ColE: "",
    ColF: "",
    Title: "Deleting subject assessments ",
    Link: " https://ehgdev.atlassian.net/wiki/spaces/SYNMAIN/pages/2294711186/Deleting+subject+assessments",
    LongDescription: "",
    SummaryDescription: "summary",
    ParentNodeString: "1.6",
    OriginalNumber: "1.6.12",
    GroupingID: "1065",
  },
  {
    ColA: "",
    ColB: "1.7",
    ColC: "",
    ColD: "",
    ColE: "",
    ColF: "",
    Title: "Maintaining subject assessment areas ",
    Link: " https://ehgdev.atlassian.net/wiki/spaces/SYNMAIN/pages/2294711046/Maintaining+subject+assessment+areas",
    LongDescription:
      "Subjects and subject assessment areas have a one-to-one relationship; there can only be one set of criteria for assessing a subject in each reporting period. See Maintaining subject assessments. Any class can use an assessment area and all students in that class can have results entered for their work throughout each reporting period.",
    SummaryDescription: "summary",
    ParentNodeString: "1",
    OriginalNumber: "1.7",
    GroupingID: "337",
  },
  {
    ColA: "",
    ColB: "",
    ColC: "1.7.1",
    ColD: "",
    ColE: "",
    ColF: "",
    Title: "Creating new subject assessment areas ",
    Link: " https://ehgdev.atlassian.net/wiki/spaces/SYNMAIN/pages/2294711184/Creating+new+subject+assessment+areas",
    LongDescription: "",
    SummaryDescription: "summary",
    ParentNodeString: "1.7",
    OriginalNumber: "1.7.1",
    GroupingID: "337",
  },
  {
    ColA: "",
    ColB: "",
    ColC: "1.7.2",
    ColD: "",
    ColE: "",
    ColF: "",
    Title: "Creating subject assessment areas for entering expected results ",
    Link: " https://ehgdev.atlassian.net/wiki/spaces/SYNMAIN/pages/2294736464/Creating+subject+assessment+areas+for+entering+expected+results",
    LongDescription: "",
    SummaryDescription: "summary",
    ParentNodeString: "1.7",
    OriginalNumber: "1.7.2",
    GroupingID: "337",
  },
  {
    ColA: "",
    ColB: "",
    ColC: "1.7.3",
    ColD: "",
    ColE: "",
    ColF: "",
    Title: "Inserting new subject assessment areas ",
    Link: " https://ehgdev.atlassian.net/wiki/spaces/SYNMAIN/pages/2294711183/Inserting+new+subject+assessment+areas",
    LongDescription: "",
    SummaryDescription: "summary",
    ParentNodeString: "1.7",
    OriginalNumber: "1.7.3",
    GroupingID: "337",
  },
  {
    ColA: "",
    ColB: "",
    ColC: "1.7.4",
    ColD: "",
    ColE: "",
    ColF: "",
    Title: "Creating new Victorian Curriculum F-10 subject assessment areas ",
    Link: " https://ehgdev.atlassian.net/wiki/spaces/SYNMAIN/pages/2294736494/Creating+new+Victorian+Curriculum+F-10+subject+assessment+areas",
    LongDescription: "",
    SummaryDescription: "summary",
    ParentNodeString: "1.7",
    OriginalNumber: "1.7.4",
    GroupingID: "337",
  },
  {
    ColA: "",
    ColB: "",
    ColC: "1.7.5",
    ColD: "",
    ColE: "",
    ColF: "",
    Title: "Subject Assessment Maintenance - Area tab - Area sub-tab ",
    Link: " https://ehgdev.atlassian.net/wiki/spaces/SYNMAIN/pages/2294711042/Subject+Assessment+Maintenance+-+Area+tab+-+Area+sub-tab",
    LongDescription: "",
    SummaryDescription: "summary",
    ParentNodeString: "1.7",
    OriginalNumber: "1.7.5",
    GroupingID: "337",
  },
  {
    ColA: "",
    ColB: "",
    ColC: "",
    ColD: "1.7.5.1",
    ColE: "",
    ColF: "",
    Title: "Moving an assessment area to another sequence ",
    Link: " https://ehgdev.atlassian.net/wiki/spaces/SYNMAIN/pages/2294711044/Moving+an+assessment+area+to+another+sequence",
    LongDescription: "",
    SummaryDescription: "summary",
    ParentNodeString: "1.7.5",
    OriginalNumber: "1.7.5.1",
    GroupingID: "337",
  },
  {
    ColA: "",
    ColB: "",
    ColC: "",
    ColD: "1.7.5.2",
    ColE: "",
    ColF: "",
    Title: "Merging other assessment areas into the current assessment area ",
    Link: " https://ehgdev.atlassian.net/wiki/spaces/SYNMAIN/pages/2294711043/Merging+other+assessment+areas+into+the+current+assessment+area",
    LongDescription: "",
    SummaryDescription: "summary",
    ParentNodeString: "1.7.5",
    OriginalNumber: "1.7.5.2",
    GroupingID: "337",
  },
  {
    ColA: "",
    ColB: "",
    ColC: "",
    ColD: "1.7.5.3",
    ColE: "",
    ColF: "",
    Title: "Inserting new subject assessment areas from the Area sub-tab ",
    Link: " https://ehgdev.atlassian.net/wiki/spaces/SYNMAIN/pages/2294711041/Inserting+new+subject+assessment+areas+from+the+Area+sub-tab",
    LongDescription: "",
    SummaryDescription: "summary",
    ParentNodeString: "1.7.5",
    OriginalNumber: "1.7.5.3",
    GroupingID: "337",
  },
  {
    ColA: "",
    ColB: "",
    ColC: "1.7.6",
    ColD: "",
    ColE: "",
    ColF: "",
    Title: "Subject Assessment Maintenance - Area tab - Formula sub-tab ",
    Link: " https://ehgdev.atlassian.net/wiki/spaces/SYNMAIN/pages/2294711045/Subject+Assessment+Maintenance+-+Area+tab+-+Formula+sub-tab",
    LongDescription:
      "Space where staff can adjust assessment task weightings and rankings. If required, several subject assessments can be linked together via the Summarise to Area field on the Subject Assessment Maintenance window. The marks awarded for each subject assessment are combined together to produce a single calculated result which can be displayed on a student's report. Each subject assessment is assigned a weighting factor that will determine the priority given to each of the subject assessments when combining them for the total calculated result.",
    SummaryDescription: "summary",
    ParentNodeString: "1.7",
    OriginalNumber: "1.7.6",
    GroupingID: "545",
  },
  {
    ColA: "",
    ColB: "",
    ColC: "",
    ColD: "1.7.6.1",
    ColE: "",
    ColF: "",
    Title: "New method of calculating and summarising assessment areas ",
    Link: " https://ehgdev.atlassian.net/wiki/spaces/SYNMAIN/pages/2294711048/New+method+of+calculating+and+summarising+assessment+areas",
    LongDescription: "",
    SummaryDescription: "summary",
    ParentNodeString: "1.7.6",
    OriginalNumber: "1.7.6.1",
    GroupingID: "545",
  },
  {
    ColA: "",
    ColB: "",
    ColC: "",
    ColD: "",
    ColE: "1.7.6.1.1",
    ColF: "",
    Title: "Functions used when calculating student results ",
    Link: " https://ehgdev.atlassian.net/wiki/spaces/SYNMAIN/pages/2294711047/Functions+used+when+calculating+student+results",
    LongDescription: "",
    SummaryDescription: "summary",
    ParentNodeString: "1.7.6.1",
    OriginalNumber: "1.7.6.1.1",
    GroupingID: "545",
  },
  {
    ColA: "",
    ColB: "",
    ColC: "",
    ColD: "",
    ColE: "1.7.6.1.2",
    ColF: "",
    Title: "Adding a weighted average formula to student results ",
    Link: " https://ehgdev.atlassian.net/wiki/spaces/SYNMAIN/pages/2294711049/Adding+a+weighted+average+formula+to+student+results",
    LongDescription: "",
    SummaryDescription: "summary",
    ParentNodeString: "1.7.6.1",
    OriginalNumber: "1.7.6.1.2",
    GroupingID: "545",
  },
  {
    ColA: "",
    ColB: "",
    ColC: "",
    ColD: "",
    ColE: "1.7.6.1.3",
    ColF: "",
    Title: "Adding a ranking formula to student results ",
    Link: " https://ehgdev.atlassian.net/wiki/spaces/SYNMAIN/pages/2294711053/Adding+a+ranking+formula+to+student+results",
    LongDescription: "",
    SummaryDescription: "summary",
    ParentNodeString: "1.7.6.1",
    OriginalNumber: "1.7.6.1.3",
    GroupingID: "545",
  },
  {
    ColA: "",
    ColB: "",
    ColC: "",
    ColD: "",
    ColE: "1.7.6.1.4",
    ColF: "",
    Title: "Adding a decile or similar formula to student results ",
    Link: " https://ehgdev.atlassian.net/wiki/spaces/SYNMAIN/pages/2294711052/Adding+a+decile+or+similar+formula+to+student+results",
    LongDescription: "",
    SummaryDescription: "summary",
    ParentNodeString: "1.7.6.1",
    OriginalNumber: "1.7.6.1.4",
    GroupingID: "545",
  },
  {
    ColA: "",
    ColB: "",
    ColC: "",
    ColD: "1.7.6.2",
    ColE: "",
    ColF: "",
    Title: "Traditional method of summarising and linking assessment areas ",
    Link: " https://ehgdev.atlassian.net/wiki/spaces/SYNMAIN/pages/2294711050/Traditional+method+of+summarising+and+linking+assessment+areas",
    LongDescription: "",
    SummaryDescription: "summary",
    ParentNodeString: "1.7.6",
    OriginalNumber: "1.7.6.2",
    GroupingID: "545",
  },
  {
    ColA: "",
    ColB: "",
    ColC: "",
    ColD: "",
    ColE: "1.7.6.2.1",
    ColF: "",
    Title:
      "Linking subject assessment areas using the Summarise to Area field ",
    Link: " https://ehgdev.atlassian.net/wiki/spaces/SYNMAIN/pages/2294711051/Linking+subject+assessment+areas+using+the+Summarise+to+Area+field",
    LongDescription: "",
    SummaryDescription: "summary",
    ParentNodeString: "1.7.6.2",
    OriginalNumber: "1.7.6.2.1",
    GroupingID: "545",
  },
  {
    ColA: "",
    ColB: "",
    ColC: "",
    ColD: "",
    ColE: "1.7.6.2.2",
    ColF: "",
    Title:
      "Linking several subject assessment results to produce a single combined mark ",
    Link: " https://ehgdev.atlassian.net/wiki/spaces/SYNMAIN/pages/2294711058/Linking+several+subject+assessment+results+to+produce+a+single+combined+mark",
    LongDescription: "",
    SummaryDescription: "summary",
    ParentNodeString: "1.7.6.2",
    OriginalNumber: "1.7.6.2.2",
    GroupingID: "545",
  },
  {
    ColA: "",
    ColB: "",
    ColC: "",
    ColD: "1.7.6.3",
    ColE: "",
    ColF: "",
    Title: "Creating a numeric result type for calculated assessment areas ",
    Link: " https://ehgdev.atlassian.net/wiki/spaces/SYNMAIN/pages/2294711059/Creating+a+numeric+result+type+for+calculated+assessment+areas",
    LongDescription: "",
    SummaryDescription: "summary",
    ParentNodeString: "1.7.6",
    OriginalNumber: "1.7.6.3",
    GroupingID: "545",
  },
  {
    ColA: "",
    ColB: "",
    ColC: "1.7.7",
    ColD: "",
    ColE: "",
    ColF: "",
    Title: "Subject Assessment Maintenance - Area tab - Comments sub-tab ",
    Link: " https://ehgdev.atlassian.net/wiki/spaces/SYNMAIN/pages/2294711057/Subject+Assessment+Maintenance+-+Area+tab+-+Comments+sub-tab",
    LongDescription:
      "Use the Comments sub-tab of the Area tab to create a comment bank for the various subject assessments or areas. Comment banks can also be linked to a subject or to a staff member. There are two Comments sub-tabs in the Subject Assessment Maintenance window: The sub-tab on the Area tab, which is used for adding comments for assessment areas. For example, comments for the exam assessment area. The sub-tab on the Summary tab, which is used for adding overall comments for subject assessments. For example, comments for a subject such as English. The comment bank allows teachers to select pre-approved comments to include in their reports. Use the Awards sub-tab to maintain award points that are allocated to students when they participate in certain classes. For example, completing a fundraising class may earn points towards a Service award. You can also use the Awards sub-tab to enter information about criteria that a student has fulfilled as part of automatic award allocation. For example, by setting up a subject assessment area for Open Day participation, points may be allocated towards School Leadership. Use the Domains sub-tab to: view domains linked to the area select or clear the Summarise field (column) which determines whether the results are reported at the domain level. Use the Material sub-tab to maintain a record of the materials required for an external or internal course or subject. Materials can be text books, stationery, art supplies and so on. Use the DocMan tab to view, import, export, update and delete documents, pictures and spreadsheets related to subject assessment areas. Use the User Forms tab to open forms that have been created at your organisation. Use the Documents tab to list documents that relate to all classes using the subject assessment code. Documents listed here are displayed in a class list under the Results tab of the community portal for all students taking a class that uses this subject assessment code. You can use the Subject Assessment Other Definition Maintenance window to copy subject assessment definitions from one year to the current year.",
    SummaryDescription: "summary",
    ParentNodeString: "1.7",
    OriginalNumber: "1.7.7",
    GroupingID: "2113",
  },
  {
    ColA: "",
    ColB: "",
    ColC: "1.7.8",
    ColD: "",
    ColE: "",
    ColF: "",
    Title: "Subject Assessment Maintenance - Area tab - Awards sub-tab ",
    Link: " https://ehgdev.atlassian.net/wiki/spaces/SYNMAIN/pages/2294711056/Subject+Assessment+Maintenance+-+Area+tab+-+Awards+sub-tab",
    LongDescription: "",
    SummaryDescription: "summary",
    ParentNodeString: "1.7",
    OriginalNumber: "1.7.8",
    GroupingID: "2113",
  },
  {
    ColA: "",
    ColB: "",
    ColC: "1.7.9",
    ColD: "",
    ColE: "",
    ColF: "",
    Title: "Subject Assessment Maintenance - Area tab - Domains sub-tab ",
    Link: " https://ehgdev.atlassian.net/wiki/spaces/SYNMAIN/pages/2294711054/Subject+Assessment+Maintenance+-+Area+tab+-+Domains+sub-tab",
    LongDescription: "",
    SummaryDescription: "summary",
    ParentNodeString: "1.7",
    OriginalNumber: "1.7.9",
    GroupingID: "2113",
  },
  {
    ColA: "",
    ColB: "",
    ColC: "1.7.10",
    ColD: "",
    ColE: "",
    ColF: "",
    Title: "Subject Assessment Maintenance - Area tab - Statistics sub-tab ",
    Link: " https://ehgdev.atlassian.net/wiki/spaces/SYNMAIN/pages/2294711055/Subject+Assessment+Maintenance+-+Area+tab+-+Statistics+sub-tab",
    LongDescription: "",
    SummaryDescription: "summary",
    ParentNodeString: "1.7",
    OriginalNumber: "1.7.10",
    GroupingID: "2113",
  },
  {
    ColA: "",
    ColB: "",
    ColC: "1.7.11",
    ColD: "",
    ColE: "",
    ColF: "",
    Title: "Subject Assessment Maintenance - Area tab - Material sub-tab ",
    Link: " https://ehgdev.atlassian.net/wiki/spaces/SYNMAIN/pages/2294711061/Subject+Assessment+Maintenance+-+Area+tab+-+Material+sub-tab",
    LongDescription: "",
    SummaryDescription: "summary",
    ParentNodeString: "1.7",
    OriginalNumber: "1.7.11",
    GroupingID: "2113",
  },
  {
    ColA: "",
    ColB: "",
    ColC: "1.7.12",
    ColD: "",
    ColE: "",
    ColF: "",
    Title: "Subject Assessment Maintenance - Area tab - DocMan sub-tab ",
    Link: " https://ehgdev.atlassian.net/wiki/spaces/SYNMAIN/pages/2294711060/Subject+Assessment+Maintenance+-+Area+tab+-+DocMan+sub-tab",
    LongDescription: "",
    SummaryDescription: "summary",
    ParentNodeString: "1.7",
    OriginalNumber: "1.7.12",
    GroupingID: "2113",
  },
]
