// make sure to leave the o master node!!
export const data_pop = [
    {
      ColA: "0",
      ColB: "0",
      ColC: "0",
      ColD: "0",
      ColE: "0",
      ColF: "0",
      Title: "MasterNode",
      Link: "https://google.com",
      LongDescription: "MasterNode",
      SummaryDescription: "MasterNode",
      ParentNodeString: "0",
      OriginalNumber: "0",
    },
    {
      ColA: "1",
      ColB: "",
      ColC: "",
      ColD: "",
      ColE: "",
      ColF: "",
      Title: "Assessments and reports ",
      Link: " https://ehgdev.atlassian.net/wiki/spaces/SYNMAIN/pages/2294710291/Assessments+and+reports ",
      LongDescription: "long desc",
      SummaryDescription: "summary",
      ParentNodeString: "0",
      OriginalNumber: "1",
    },
    {
      ColA: "",
      ColB: "1.1",
      ColC: "",
      ColD: "",
      ColE: "",
      ColF: "",
      Title: "Assessments and reports Overview ",
      Link: " https://ehgdev.atlassian.net/wiki/spaces/SYNMAIN/pages/2294711167/Assessments+and+reports+Overview",
      LongDescription: "",
      SummaryDescription: "summary",
      ParentNodeString: "1",
      OriginalNumber: "1.1",
    },
    {
      ColA: "",
      ColB: "1.2",
      ColC: "",
      ColD: "",
      ColE: "",
      ColF: "",
      Title: "Whats new to Assessments and reports ",
      Link: " https://ehgdev.atlassian.net/wiki/spaces/SYNMAIN/pages/2294738607/What%27s+new+to+Assessments+and+reports",
      LongDescription: "",
      SummaryDescription: "summary",
      ParentNodeString: "1",
      OriginalNumber: "1.2",
    },
    {
      ColA: "",
      ColB: "1.3",
      ColC: "",
      ColD: "",
      ColE: "",
      ColF: "",
      Title: "Concepts used in student assessments ",
      Link: " https://ehgdev.atlassian.net/wiki/spaces/SYNMAIN/pages/2294711168/Concepts+used+in+student+assessments",
      LongDescription: "",
      SummaryDescription: "summary",
      ParentNodeString: "1",
      OriginalNumber: "1.3",
    },
    {
      ColA: "",
      ColB: "1.4",
      ColC: "",
      ColD: "",
      ColE: "",
      ColF: "",
      Title: "Victorian Curriculum F-10 ",
      Link: " https://ehgdev.atlassian.net/wiki/spaces/SYNMAIN/pages/2294736348/Victorian+Curriculum+F-10",
      LongDescription: "",
      SummaryDescription: "summary",
      ParentNodeString: "1",
      OriginalNumber: "1.4",
    },
    {
      ColA: "",
      ColB: "",
      ColC: "1.4.1",
      ColD: "",
      ColE: "",
      ColF: "",
      Title: "Victorian Curriculum frameworks ",
      Link: " https://ehgdev.atlassian.net/wiki/spaces/SYNMAIN/pages/2294736370/Victorian+Curriculum+frameworks",
      LongDescription: "",
      SummaryDescription: "summary",
      ParentNodeString: "1.4",
      OriginalNumber: "1.4.1",
    },
    {
      ColA: "",
      ColB: "",
      ColC: "",
      ColD: "1.4.1.1",
      ColE: "",
      ColF: "",
      Title: "Maintaining Victorian Curriculum frameworks ",
      Link: " https://ehgdev.atlassian.net/wiki/spaces/SYNMAIN/pages/2294736369/Maintaining+Victorian+Curriculum+frameworks",
      LongDescription: "",
      SummaryDescription: "summary",
      ParentNodeString: "1.4.1",
      OriginalNumber: "1.4.1.1",
    },
    {
      ColA: "",
      ColB: "",
      ColC: "1.4.2",
      ColD: "",
      ColE: "",
      ColF: "",
      Title: "Victorian Curriculum reporting requirements ",
      Link: " https://ehgdev.atlassian.net/wiki/spaces/SYNMAIN/pages/2294741917/Victorian+Curriculum+reporting+requirements",
      LongDescription: "",
      SummaryDescription: "summary",
      ParentNodeString: "1.4",
      OriginalNumber: "1.4.2",
    },
    {
      ColA: "",
      ColB: "",
      ColC: "1.4.3",
      ColD: "",
      ColE: "",
      ColF: "",
      Title: "Configuring the Victorian Curriculum ",
      Link: " https://ehgdev.atlassian.net/wiki/spaces/SYNMAIN/pages/2294741920/Configuring+the+Victorian+Curriculum",
      LongDescription: "",
      SummaryDescription: "summary",
      ParentNodeString: "1.4",
      OriginalNumber: "1.4.3",
    },
    {
      ColA: "",
      ColB: "",
      ColC: "1.4.4",
      ColD: "",
      ColE: "",
      ColF: "",
      Title: "Entering Victorian Curriculum results ",
      Link: " https://ehgdev.atlassian.net/wiki/spaces/SYNMAIN/pages/2294736398/Entering+Victorian+Curriculum+results",
      LongDescription: "",
      SummaryDescription: "summary",
      ParentNodeString: "1.4",
      OriginalNumber: "1.4.4",
    },
    {
      ColA: "",
      ColB: "",
      ColC: "",
      ColD: "1.4.4.1",
      ColE: "",
      ColF: "",
      Title: "Adding the DNP result to the luReportResultType lookup table ",
      Link: " https://ehgdev.atlassian.net/wiki/spaces/SYNMAIN/pages/2294736397/Adding+the+DNP+result+to+the+luReportResultType+lookup+table",
      LongDescription: "",
      SummaryDescription: "summary",
      ParentNodeString: "1.4.4",
      OriginalNumber: "1.4.4.1",
    },
    {
      ColA: "",
      ColB: "",
      ColC: "1.4.5",
      ColD: "",
      ColE: "",
      ColF: "",
      Title: "Related information for Victorian Curriculum ",
      Link: " https://ehgdev.atlassian.net/wiki/spaces/SYNMAIN/pages/2294741929/Related+information+for+Victorian+Curriculum",
      LongDescription: "",
      SummaryDescription: "summary",
      ParentNodeString: "1.4",
      OriginalNumber: "1.4.5",
    },
    {
      ColA: "",
      ColB: "1.5",
      ColC: "",
      ColD: "",
      ColE: "",
      ColF: "",
      Title: "Maintaining curriculum frameworks ",
      Link: " https://ehgdev.atlassian.net/wiki/spaces/SYNMAIN/pages/2294736408/Maintaining+curriculum+frameworks",
      LongDescription: "curriculum framework",
      SummaryDescription: "summary",
      ParentNodeString: "1",
      OriginalNumber: "1.5",
    },
    {
      ColA: "",
      ColB: "",
      ColC: "1.5.1",
      ColD: "",
      ColE: "",
      ColF: "",
      Title: "Using the Subject Assessment Other Definition Maintenance window ",
      Link: " https://ehgdev.atlassian.net/wiki/spaces/SYNMAIN/pages/2294736410/Using+the+Subject+Assessment+Other+Definition+Maintenance+window",
      LongDescription: "",
      SummaryDescription: "summary",
      ParentNodeString: "1.5",
      OriginalNumber: "1.5.1",
    },
    {
      ColA: "",
      ColB: "",
      ColC: "",
      ColD: "1.5.1.1",
      ColE: "",
      ColF: "",
      Title: "Loading pre-defined curriculum frameworks ",
      Link: " https://ehgdev.atlassian.net/wiki/spaces/SYNMAIN/pages/2294736424/Loading+pre-defined+curriculum+frameworks",
      LongDescription: "",
      SummaryDescription: "summary",
      ParentNodeString: "1.5.1",
      OriginalNumber: "1.5.1.1",
    },
    {
      ColA: "",
      ColB: "",
      ColC: "",
      ColD: "1.5.1.2",
      ColE: "",
      ColF: "",
      Title: "Copying existing curriculum frameworks to new years ",
      Link: " https://ehgdev.atlassian.net/wiki/spaces/SYNMAIN/pages/2294736436/Copying+existing+curriculum+frameworks+to+new+years",
      LongDescription: "",
      SummaryDescription: "summary",
      ParentNodeString: "1.5.1",
      OriginalNumber: "1.5.1.2",
    },
    {
      ColA: "",
      ColB: "",
      ColC: "",
      ColD: "1.5.1.3",
      ColE: "",
      ColF: "",
      Title: "Manually adding custom levels to curriculum frameworks ",
      Link: " https://ehgdev.atlassian.net/wiki/spaces/SYNMAIN/pages/2294736445/Manually+adding+custom+levels+to+curriculum+frameworks",
      LongDescription: "",
      SummaryDescription: "summary",
      ParentNodeString: "1.5.1",
      OriginalNumber: "1.5.1.3",
    },
    {
      ColA: "",
      ColB: "1.6",
      ColC: "",
      ColD: "",
      ColE: "",
      ColF: "",
      Title: "Maintaining subject assessments ",
      Link: " https://ehgdev.atlassian.net/wiki/spaces/SYNMAIN/pages/2294711169/Maintaining+subject+assessments",
      LongDescription: "learning area",
      SummaryDescription: "summary",
      ParentNodeString: "1",
      OriginalNumber: "1.6",
    },
    {
      ColA: "",
      ColB: "",
      ColC: "1.6.1",
      ColD: "",
      ColE: "",
      ColF: "",
      Title: "Searching for subjects and assessment areas ",
      Link: " https://ehgdev.atlassian.net/wiki/spaces/SYNMAIN/pages/2294711171/Searching+for+subjects+and+assessment+areas",
      LongDescription: "",
      SummaryDescription: "summary",
      ParentNodeString: "1.6",
      OriginalNumber: "1.6.1",
    },
    {
      ColA: "",
      ColB: "",
      ColC: "1.6.2",
      ColD: "",
      ColE: "",
      ColF: "",
      Title: "Creating new subject assessments ",
      Link: " https://ehgdev.atlassian.net/wiki/spaces/SYNMAIN/pages/2294711170/Creating+new+subject+assessments",
      LongDescription: "",
      SummaryDescription: "summary",
      ParentNodeString: "1.6",
      OriginalNumber: "1.6.2",
    },
    {
      ColA: "",
      ColB: "",
      ColC: "1.6.3",
      ColD: "",
      ColE: "",
      ColF: "",
      Title: "Subject Assessment Maintenance - Summary tab - Summary sub-tab ",
      Link: " https://ehgdev.atlassian.net/wiki/spaces/SYNMAIN/pages/2294711172/Subject+Assessment+Maintenance+-+Summary+tab+-+Summary+sub-tab",
      LongDescription: "",
      SummaryDescription: "summary",
      ParentNodeString: "1.6",
      OriginalNumber: "1.6.3",
    },
    {
      ColA: "",
      ColB: "",
      ColC: "1.6.4",
      ColD: "",
      ColE: "",
      ColF: "",
      Title: "Subject Assessment Maintenance - Summary tab - Comments sub-tab ",
      Link: " https://ehgdev.atlassian.net/wiki/spaces/SYNMAIN/pages/2294711174/Subject+Assessment+Maintenance+-+Summary+tab+-+Comments+sub-tab",
      LongDescription: "",
      SummaryDescription: "summary",
      ParentNodeString: "1.6",
      OriginalNumber: "1.6.4",
    },
    {
      ColA: "",
      ColB: "",
      ColC: "",
      ColD: "1.6.4.1",
      ColE: "",
      ColF: "",
      Title: "Comment bank ",
      Link: " https://ehgdev.atlassian.net/wiki/spaces/SYNMAIN/pages/2294711173/Comment+bank",
      LongDescription: "",
      SummaryDescription: "summary",
      ParentNodeString: "1.6.4",
      OriginalNumber: "1.6.4.1",
    },
    {
      ColA: "",
      ColB: "",
      ColC: "",
      ColD: "1.6.4.2",
      ColE: "",
      ColF: "",
      Title: "Loading and copying existing comments ",
      Link: " https://ehgdev.atlassian.net/wiki/spaces/SYNMAIN/pages/2294711176/Loading+and+copying+existing+comments",
      LongDescription: "",
      SummaryDescription: "summary",
      ParentNodeString: "1.6.4",
      OriginalNumber: "1.6.4.2",
    },
    {
      ColA: "",
      ColB: "",
      ColC: "1.6.5",
      ColD: "",
      ColE: "",
      ColF: "",
      Title: "Subject Assessment Maintenance - Summary tab - Mark Book sub-tab ",
      Link: " https://ehgdev.atlassian.net/wiki/spaces/SYNMAIN/pages/2294711175/Subject+Assessment+Maintenance+-+Summary+tab+-+Mark+Book+sub-tab",
      LongDescription: "",
      SummaryDescription: "summary",
      ParentNodeString: "1.6",
      OriginalNumber: "1.6.5",
    },
    {
      ColA: "",
      ColB: "",
      ColC: "",
      ColD: "1.6.5.1",
      ColE: "",
      ColF: "",
      Title:
        "Importing mark book assessments from Subject Assessment Maintenance ",
      Link: " https://ehgdev.atlassian.net/wiki/spaces/SYNMAIN/pages/2294711179/Importing+mark+book+assessments+from+Subject+Assessment+Maintenance",
      LongDescription: "",
      SummaryDescription: "summary",
      ParentNodeString: "1.6.5",
      OriginalNumber: "1.6.5.1",
    },
    {
      ColA: "",
      ColB: "",
      ColC: "1.6.6",
      ColD: "",
      ColE: "",
      ColF: "",
      Title: "Subject Assessment Maintenance - Summary tab - Classes sub-tab ",
      Link: " https://ehgdev.atlassian.net/wiki/spaces/SYNMAIN/pages/2294711178/Subject+Assessment+Maintenance+-+Summary+tab+-+Classes+sub-tab",
      LongDescription: "",
      SummaryDescription: "summary",
      ParentNodeString: "1.6",
      OriginalNumber: "1.6.6",
    },
    {
      ColA: "",
      ColB: "",
      ColC: "1.6.7",
      ColD: "",
      ColE: "",
      ColF: "",
      Title: "Subject Assessment Maintenance - Summary tab - Targets sub-tab ",
      Link: " https://ehgdev.atlassian.net/wiki/spaces/SYNMAIN/pages/2294711177/Subject+Assessment+Maintenance+-+Summary+tab+-+Targets+sub-tab",
      LongDescription: "",
      SummaryDescription: "summary",
      ParentNodeString: "1.6",
      OriginalNumber: "1.6.7",
    },
    {
      ColA: "",
      ColB: "",
      ColC: "1.6.8",
      ColD: "",
      ColE: "",
      ColF: "",
      Title: "Subject Assessment Maintenance - Summary tab - Security sub-tab ",
      Link: " https://ehgdev.atlassian.net/wiki/spaces/SYNMAIN/pages/2294711182/Subject+Assessment+Maintenance+-+Summary+tab+-+Security+sub-tab",
      LongDescription: "",
      SummaryDescription: "summary",
      ParentNodeString: "1.6",
      OriginalNumber: "1.6.8",
    },
    {
      ColA: "",
      ColB: "",
      ColC: "1.6.9",
      ColD: "",
      ColE: "",
      ColF: "",
      Title: "Renaming subject assessments ",
      Link: " https://ehgdev.atlassian.net/wiki/spaces/SYNMAIN/pages/2294711181/Renaming+subject+assessments",
      LongDescription: "",
      SummaryDescription: "summary",
      ParentNodeString: "1.6",
      OriginalNumber: "1.6.9",
    },
  ]